import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is autogenerated from the docs/ folder structure:
 *  - docs/intro.md                -> Введение (root)
 *  - docs/part-1-rag/*            -> Часть I — RAG
 *  - docs/part-2-agents/*         -> Часть II — Агенты
 *  - docs/part-3-production/*     -> Часть III — Production и LLMOps
 *  - docs/glossary.md            -> Глоссарий
 * Ordering comes from `sidebar_position` frontmatter and `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  handbookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
