import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * The sidebar is autogenerated from the `docs/` folder structure (EN, the default
 * locale; the RU labels below come from the mirror under
 * `i18n/ru/docusaurus-plugin-content-docs/current/`):
 *  - docs/intro.md                -> Introduction / Введение (root)
 *  - docs/part-1-rag/*            -> Part I — RAG / Часть I — RAG
 *  - docs/part-2-agents/*         -> Part II — Agents / Часть II — Агенты
 *  - docs/part-3-production/*     -> Part III — Production & LLMOps / Часть III — Production и LLMOps
 *  - docs/glossary.md            -> Glossary / Глоссарий
 * Ordering comes from `sidebar_position` frontmatter and `_category_.json`.
 */
const sidebars: SidebarsConfig = {
  handbookSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
