import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// This runs in Node.js - Don't use client-side code here (browser APIs, JSX...)

/**
 * Sidebar for the AI SDLC course (docs instance id `ai-sdlc`, served at
 * `/ai-sdlc`). Autogenerated from the `docs-ai-sdlc/` folder, exactly like the
 * RAG course's sidebar. Today the course is a single Intro stub; as Part I is
 * authored, its lessons appear here automatically from the folder structure
 * (`sidebar_position` frontmatter + `_category_.json` order).
 */
const sidebars: SidebarsConfig = {
  aiSdlcSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
